#server:
#  port: 8086

spring:
  main:
    banner-mode: console
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    platform: h2
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=PostgreSQL;DB_CLOSE_ON_EXIT=TRUE
#  datasource:
#    url: jdbc:mysql://localhost:3306/playground?serverTimezone=UTC
#    username: useris
#    password:
#    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    generate-ddl: true

logging:
  level:
    org:
      springframework: ERROR